### ISSUE TITLE
Gestion fiche de travail type

### ISSUE THREAD

**Issue by herissondev** [ADCL-FR/SITE#73]
à re-découper en plsieur taches

Il faudrait créer une rubrique : FICHE DE TRAVAIL TYPE => nous avons des affaires récurrentes et il y a donc des fiches qui sont toujours identiques : l’idée est donc d’avoir une base de données avec des fiches déjà réaliser, préremplis (et modifiable au besoin)

**Comment by aime-risson** [comment]
- [ ] ajout page de liste modele fiche type
- [ ] ajout création modele fiche type
- [ ] ajout création étape
- [ ] ajout fonctionnalité copie / création de fiche à partir des modèles
